# Generated by Django 6.0.6 on 2026-07-05 12:19

import accounts_app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('id_document', 'ID Document'), ('rental_contract', 'Rental Contract')], max_length=20)),
                ('file', models.FileField(upload_to=accounts_app.models.verification_document_path)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('country', models.CharField(blank=True, choices=[('egyptian', 'Egyptian'), ('palestinian', 'Palestinian'), ('saudi', 'Saudi Arabian'), ('jordanian', 'Jordanian'), ('syrian', 'Syrian'), ('emirati', 'Emirati'), ('moroccan', 'Moroccan'), ('other', 'Other')], max_length=100, null=True)),
                ('auth_provider', models.CharField(choices=[('email', 'Email/Password'), ('google', 'Google')], default='email', max_length=10)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LifestyleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleep_time', models.CharField(choices=[('early', 'Before 10PM'), ('normal', '10PM–12AM'), ('late', 'After 12AM')], max_length=10)),
                ('wake_time', models.CharField(blank=True, choices=[('early', 'Before 7AM'), ('normal', '7AM–9AM'), ('late', 'After 9AM')], max_length=10, null=True)),
                ('noise_level', models.CharField(choices=[('quiet', 'Quiet'), ('moderate', 'Moderate'), ('noisy', 'Noisy')], max_length=10)),
                ('social_type', models.CharField(choices=[('private', 'Introvert'), ('moderate', 'Balanced'), ('social', 'Extrovert')], max_length=10)),
                ('cleanliness', models.CharField(choices=[('very_clean', 'Very clean'), ('clean', 'Clean'), ('relaxed', 'Relaxed')], max_length=12)),
                ('cooking', models.BooleanField(default=False)),
                ('pets', models.BooleanField(default=False)),
                ('smoking', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('outside_only', 'Outside only')], default='no', max_length=12)),
                ('preferred_roommates', models.CharField(choices=[('1', '1 roommate'), ('2', '2 roommates'), ('3', '3 roommates'), ('4+', '4+ roommates')], max_length=2)),
                ('religion', models.CharField(blank=True, choices=[('muslim_committed', 'Muslim (practicing)'), ('muslim_not_committed', 'Muslim (non-practicing)'), ('christian', 'Christian'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=25, null=True)),
                ('field', models.CharField(blank=True, choices=[('engineering', 'Engineering'), ('medicine', 'Medicine'), ('law', 'Law'), ('business', 'Business'), ('computer_science', 'Computer Science'), ('arts', 'Arts'), ('education', 'Education'), ('architecture', 'Architecture'), ('pharmacy', 'Pharmacy'), ('nursing', 'Nursing'), ('other', 'Other')], max_length=20, null=True)),
                ('roommate_gender_pref', models.CharField(choices=[('males_only', 'Males only'), ('females_only', 'Females only'), ('any', 'No preference')], max_length=15)),
                ('budget_min', models.PositiveIntegerField()),
                ('budget_max', models.PositiveIntegerField()),
                ('dietary', models.CharField(choices=[('none', 'No restrictions'), ('vegetarian', 'Vegetarian'), ('halal', 'Halal only'), ('no_seafood', 'No seafood')], max_length=15)),
                ('guest_tolerance', models.CharField(choices=[('strict', 'Prefers few/no guests'), ('moderate', 'Occasional guests OK'), ('relaxed', 'Frequent guests OK')], max_length=10)),
                ('tenant_type', models.CharField(choices=[('students', 'Student'), ('professionals', 'Working professional'), ('families', 'Family'), ('anyone', 'Other')], max_length=15)),
                ('household_lang_pref', models.CharField(choices=[('english', 'English-speaking household'), ('arabic', 'Arabic-only household'), ('local', 'Locals preferred'), ('mixed', 'Mixed nationalities'), ('no_preference', 'No preference')], max_length=15)),
                ('alcohol_ok', models.BooleanField()),
                ('min_stay_pref', models.PositiveSmallIntegerField(choices=[(1, '1 Month'), (2, '2 Months'), (3, '3 Months'), (6, '6 Months'), (12, '1 Year'), (0, 'Flexible')])),
                ('listing_type_pref', models.CharField(choices=[('private_room', 'Private Room'), ('full_apartment', 'Full Apartment'), ('shared_bed', 'Shared Bed'), ('roommate_wanted', 'Roommate Wanted')], max_length=20)),
                ('works_from_home', models.BooleanField()),
                ('wants_furnished', models.BooleanField()),
                ('wants_building_amenities', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lifestyle_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lifestyle_profile',
            },
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
