# Generated by Django 6.0.6 on 2026-07-04 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts_app', '0001_initial'),
        ('listings_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationdocument',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_documents', to='listings_app.listing'),
        ),
        migrations.AddField(
            model_name='verificationdocument',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='verificationdocument',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='verificationdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('document_type', 'id_document')), fields=('user', 'document_type'), name='unique_id_document_per_user'),
        ),
        migrations.AddConstraint(
            model_name='verificationdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('document_type', 'rental_contract')), fields=('listing', 'document_type'), name='unique_rental_contract_per_listing'),
        ),
    ]
