# Generated by Django 6.0.6 on 2026-07-02 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0001_initial'),
        ('listings_app', '0003_alter_listing_id_alter_listingimage_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='verificationdocument',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='verificationdocument',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_documents', to='listings_app.listing'),
        ),
        migrations.AddConstraint(
            model_name='verificationdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('document_type', 'id_document')), fields=('user', 'document_type'), name='unique_id_document_per_user'),
        ),
        migrations.AddConstraint(
            model_name='verificationdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('document_type', 'rental_contract')), fields=('listing', 'document_type'), name='unique_rental_contract_per_listing'),
        ),
    ]
