# Generated by Django 6.0.6 on 2026-06-26 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='LifestyleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleep_time', models.CharField(choices=[('early', 'Before 10PM'), ('normal', '10PM–12AM'), ('late', 'After 12AM')], max_length=10)),
                ('wake_time', models.CharField(blank=True, choices=[('early', 'Before 7AM'), ('normal', '7AM–9AM'), ('late', 'After 9AM')], max_length=10, null=True)),
                ('noise_level', models.CharField(choices=[('quiet', 'Quiet'), ('moderate', 'Moderate'), ('noisy', 'Noisy')], max_length=10)),
                ('social_type', models.CharField(choices=[('private', 'Introvert'), ('moderate', 'Balanced'), ('social', 'Extrovert')], max_length=10)),
                ('cleanliness', models.CharField(choices=[('very_clean', 'Very clean'), ('clean', 'Clean'), ('relaxed', 'Relaxed')], max_length=12)),
                ('cooking', models.BooleanField(default=False)),
                ('pets', models.BooleanField(default=False)),
                ('smoking', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('outside_only', 'Outside only')], default='no', max_length=12)),
                ('preferred_roommates', models.CharField(choices=[('1', '1 roommate'), ('2', '2 roommates'), ('3', '3 roommates'), ('4+', '4+ roommates')], max_length=2)),
                ('religion', models.CharField(blank=True, choices=[('muslim_committed', 'Muslim (practicing)'), ('muslim_not_committed', 'Muslim (non-practicing)'), ('christian', 'Christian'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=25, null=True)),
                ('field', models.CharField(blank=True, choices=[('engineering', 'Engineering'), ('medicine', 'Medicine'), ('law', 'Law'), ('business', 'Business'), ('computer_science', 'Computer Science'), ('arts', 'Arts'), ('education', 'Education'), ('architecture', 'Architecture'), ('pharmacy', 'Pharmacy'), ('nursing', 'Nursing'), ('other', 'Other')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lifestyle_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lifestyle_profile',
            },
        ),
    ]
