# Generated by Django 6.0.6 on 2026-06-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0002_otpcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(choices=[('email', 'Email/Password'), ('google', 'Google')], default='email', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, choices=[('egyptian', 'Egyptian'), ('palestinian', 'Palestinian'), ('saudi', 'Saudi Arabian'), ('jordanian', 'Jordanian'), ('syrian', 'Syrian'), ('emirati', 'Emirati'), ('moroccan', 'Moroccan'), ('other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
