# Generated by Django 4.2.30 on 2026-07-01 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_app", "0002_alter_lifestyleprofile_id_alter_user_id"),
        ("accounts_app", "0003_user_auth_provider_alter_user_country_and_more"),
    ]

    operations = []
