# Generated by Django 6.0.5 on 2026-07-04 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0005_alter_lifestyleprofile_id_alter_user_id'),
        ('accounts_app', '0006_lifestyleprofile_require_extended_fields'),
    ]

    operations = [
    ]
