# Generated by Django 6.0.5 on 2026-06-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='compatibility',
            field=models.PositiveSmallIntegerField(blank=True, help_text='AI compatibility score 0–100', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='poster_note',
            field=models.TextField(blank=True, help_text='Optional note from poster on accept/reject'),
        ),
        migrations.AddField(
            model_name='application',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
