# Generated by Django 6.0.5 on 2026-07-04 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications_app', '0003_alter_application_id'),
        ('applications_app', '0003_alter_application_id_listingreview'),
    ]

    operations = [
    ]
