# Generated by Django 6.0.6 on 2026-07-05 12:19

import agreements_app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications_app', '0001_initial'),
        ('listings_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_text', models.TextField(help_text='Full agreement body, Gemini-authored or template fallback')),
                ('is_fallback', models.BooleanField(default=False, help_text='True if Gemini was unavailable and a template fallback was used')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=agreements_app.models.agreement_pdf_upload_to)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('poster_signed_name', models.CharField(blank=True, max_length=150)),
                ('poster_signed_at', models.DateTimeField(blank=True, null=True)),
                ('tenant_signed_name', models.CharField(blank=True, max_length=150)),
                ('tenant_signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agreement', to='applications_app.application')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='listings_app.listing')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements_as_poster', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements_as_tenant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
