# Generated by Django 6.0.5 on 2026-07-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='poster_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='poster_signed_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='agreement',
            name='tenant_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='tenant_signed_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
