# Generated by Django 4.2.30 on 2026-07-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agreements_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agreement",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
