# Generated by Django 6.0.6 on 2026-07-05 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_badge_text', models.CharField(default='AI-Powered Matching', max_length=60)),
                ('hero_title_line1', models.CharField(default='Find Your Perfect', max_length=80)),
                ('hero_title_line2', models.CharField(default='Roommate & Room', max_length=80)),
                ('hero_subtitle', models.TextField(default='NestMatch uses AI to match you with compatible roommates based on your lifestyle — sleep habits, cleanliness, noise level, and more.', max_length=300)),
                ('hero_cta_primary_text', models.CharField(default='Get Started', max_length=40)),
                ('hero_cta_primary_url', models.CharField(default='/auth/', max_length=200)),
                ('hero_cta_secondary_text', models.CharField(default='Browse Rooms', max_length=40)),
                ('hero_cta_secondary_url', models.CharField(default='/rooms/', max_length=200)),
                ('hero_feature_tag_1', models.CharField(default='Free to use', max_length=40)),
                ('hero_feature_tag_2', models.CharField(default='AI Compatibility', max_length=40)),
                ('hero_feature_tag_3', models.CharField(default='Instant WhatsApp', max_length=40)),
                ('stat_1_value', models.CharField(default='2,400+', max_length=20)),
                ('stat_1_label', models.CharField(default='Active Listings', max_length=40)),
                ('stat_2_value', models.CharField(default='8,500+', max_length=20)),
                ('stat_2_label', models.CharField(default='Happy Users', max_length=40)),
                ('stat_3_value', models.CharField(default='12+', max_length=20)),
                ('stat_3_label', models.CharField(default='Cities', max_length=40)),
                ('stat_4_value', models.CharField(default='94%', max_length=20)),
                ('stat_4_label', models.CharField(default='Match Accuracy', max_length=40)),
                ('how_it_works_eyebrow', models.CharField(default='How it Works', max_length=40)),
                ('how_it_works_title', models.CharField(default='Find your match in 3 simple steps', max_length=120)),
                ('how_it_works_subtitle', models.CharField(default='From sign-up to move-in, NestMatch makes the process seamless', max_length=200)),
                ('step_1_icon', models.CharField(default='📝', max_length=10)),
                ('step_1_title', models.CharField(default='Create Your Profile', max_length=60)),
                ('step_1_text', models.TextField(default='Sign up and fill out your lifestyle questionnaire — sleep time, cleanliness, noise level, smoking habits and more', max_length=250)),
                ('step_2_icon', models.CharField(default='🔍', max_length=10)),
                ('step_2_title', models.CharField(default='Browse & Match', max_length=60)),
                ('step_2_text', models.TextField(default='Search rooms with live filters. See AI compatibility scores instantly for every listing you browse', max_length=250)),
                ('step_3_icon', models.CharField(default='🤝', max_length=10)),
                ('step_3_title', models.CharField(default='Connect & Move In', max_length=60)),
                ('step_3_text', models.TextField(default='Apply to rooms, chat via WhatsApp, and generate your rental agreement with AI in seconds', max_length=250)),
                ('cta_eyebrow', models.CharField(default='Get Started Today', max_length=40)),
                ('cta_title', models.CharField(default='Ready to Find Your Perfect Nest?', max_length=120)),
                ('cta_subtitle', models.CharField(default='Join 8,500+ users already finding their perfect roommate match with AI', max_length=200)),
                ('cta_primary_text', models.CharField(default='Post a Room', max_length=40)),
                ('cta_primary_url', models.CharField(default='/rooms/new/', max_length=200)),
                ('cta_secondary_text', models.CharField(default='Find a Room', max_length=40)),
                ('cta_secondary_url', models.CharField(default='/rooms/', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Content',
                'verbose_name_plural': 'Site Content',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('seeker', 'Room Seeker'), ('poster', 'Room Poster')], max_length=10)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('quote', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_app_testimonial',
                'ordering': ['-created_at'],
            },
        ),
    ]
