# Generated by Django 6.0.5 on 2026-06-27 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='testimonial',
            table='core_app_testimonial',
        ),
    ]
