# Generated by Django 6.0.5 on 2026-07-04 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_contactmessage_alter_testimonial_id'),
        ('core_app', '0003_sitecontent'),
    ]

    operations = [
    ]
