# Generated by Django 6.0.5 on 2026-07-10 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_contactreply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='location',
        ),
    ]
