# Generated by Django 6.0.5 on 2026-07-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_merge_20260704_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
