# Generated by Django 6.0.5 on 2026-07-12 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_alter_contactmessage_id_alter_sitecontent_id_and_more'),
        ('core_app', '0007_platformsettings_site_url'),
    ]

    operations = [
    ]
