# Generated by Django 6.0.5 on 2026-07-12 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0008_merge_20260711_2043'),
        ('core_app', '0008_merge_20260712_1204'),
    ]

    operations = [
    ]
