# Generated by Django 6.0.6 on 2026-07-04 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompatibilityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.PositiveSmallIntegerField()),
                ('sleep_schedule_match', models.PositiveSmallIntegerField(default=0)),
                ('cleanliness_match', models.PositiveSmallIntegerField(default=0)),
                ('noise_match', models.PositiveSmallIntegerField(default=0)),
                ('breakdown_summary', models.TextField(blank=True)),
                ('is_fallback', models.BooleanField(default=False)),
                ('profile_updated_at', models.DateTimeField()),
                ('listing_updated_at', models.DateTimeField()),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibility_scores', to='listings_app.listing')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibility_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('seeker', 'listing')},
            },
        ),
    ]
