# Generated by Django 6.0.5 on 2026-07-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compatibility_app', '0002_alter_compatibilityscore_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compatibilityscore',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
