# Generated by Django 6.0.5 on 2026-06-26 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='available_from',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
