# Generated by Django 6.0.5 on 2026-07-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings_app', '0002_alter_listing_id_alter_listingimage_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='carbon_monoxide_alarm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='check_in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='check_out_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='first_aid_kit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='smoke_alarm',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
