# Generated by Django 6.0.5 on 2026-07-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings_app', '0003_listing_carbon_monoxide_alarm_listing_check_in_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingimage',
            name='room_label',
            field=models.CharField(choices=[('living_room', 'Living Room'), ('bedroom', 'Bedroom'), ('kitchen', 'Kitchen'), ('bathroom', 'Bathroom'), ('exterior', 'Exterior'), ('other', 'Additional Photos')], default='other', max_length=20),
        ),
    ]
