# Generated by Django 6.0.5 on 2026-07-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings_app', '0004_listingimage_room_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='floor_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='room_size_sqm',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
