# Generated by Django 6.0.5 on 2026-07-02 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings_app', '0005_listing_floor_number_listing_room_size_sqm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='floor_number',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='room_size_sqm',
        ),
    ]
